ipam:
  mode: kubernetes
hostFirewall:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
kubeProxyReplacement: true
k8sServiceHost: kubernetes.default.svc
k8sServicePort: 6443
