apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josverheij/k8s-infrastructure.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true
