operator:
  replicas: 1
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
hubble:
  peerService:
    clusterDomain: local.pakhuis.joveo.nl
etcd:
  clusterDomain: local.pakhuis.joveo.nl
cgroup:
  autoMount:
    enabled: true
  hostRoot: /sys/fs/cgroup
k8sServiceHost: api.pakhuis.joveo.nl
k8sServicePort: 6443
