apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-prod-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/josverheij/k8s-infrastructure.git
      revision: HEAD
      directories:
      - path: apps/*/envs/prod
  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}' 
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      sources:
      - repoURL: https://github.com/josverheij/k8s-infrastructure.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      - repoURL: https://github.com/josverheij/k8s-infrastructure.git
        chart: 'apps/{{ index .path.segment 1 }}/chart'
        targetRevision: HEAD
        helm:
          valueFiles:
          - '$values/apps/{{index .path.segment 1}}/chart/values.yaml'
          - '$values/apps/{{index .path.segment 1}}/base/values-common.yaml'
          - '$values/apps/{{index .path.segment 1}}/envs/{{index .path.segments 3}}/values-{{index .path.segments 3}}.yaml'
      - repoURL: https://github.com/josverheij/k8s-infrastructure.git
        targetRevision: HEAD
        ref: values

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{index .path.segments 3}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      
