apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-prod-appset-helm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/josverheij/k8s-infrastructure.git
          revision: HEAD
          directories:
          - path: values/*/envs/prod
      - clusters: {}
  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}' 
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      sources:
      - repoURL: https://github.com/josverheij/k8s-infrastructure.git
        targetRevision: HEAD
        path: 'charts/{{index .path.segments 1}}'
        helm:
          valueFiles:
          - '$values/charts/{{index .path.segments 1}}/values.yaml'
          - '$values/values/{{index .path.segments 1}}/base/values.yaml'
          - '$values/values/{{index .path.segments 1}}/envs/{{index .path.segments 3}}/values.yaml'
          # - '$values/{{.path.path}}/values-{{index .path.segments 3}}.yaml'
          - '$values/values/{{index .path.segments 1}}/clusters/values-{{.name}}.yaml'
          ignoreMissingValueFiles: true
      - repoURL: https://github.com/josverheij/k8s-infrastructure.git
        targetRevision: HEAD
        ref: values

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{if eq (index .path.segments 1) "cilium"}}kube-system{{else}}{{index .path.segments 1}}-{{index .path.segments 3}}{{end}}'
        # namespace: '{{index .path.segments 1}}-{{index .path.segments 3}}'

      # Sync policy
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            '{{if eq (index .path.segments 1) "vault"}}pod-security.kubernetes.io/enforce: privileged{{end}}'
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      
