apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-prod-appset-helm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/josverheij/k8s-infrastructure.git
          revision: HEAD
          directories:
          - files: helm/*/envs/prod/config.yaml"
      - clusters: {}
  template:      
    metadata:
      name: '{{index .path.segments 3}}-{{index .path.segments 1}}'
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      sources:
      - repoURL: https://github.com/josverheij/k8s-infrastructure.git
        targetRevision: HEAD
        ref: values
      - path: '{{.config}}{{dig "path" "." .}}'
        chart: '{{.config}}{{dig "chart" "" .}}'
        repoURL: '{{ .config.repoURL }}'
        targetRevision: '{{ .config.targetRevision }}'
        helm:
          valueFiles:
          - '$values/helm/{{index .path.segments 1}}/base/values.yaml'
          - '$values/helm/{{index .path.segments 1}}/envs/{{index .path.segments 3}}/values.yaml'
          # - '$values/{{.path.path}}/values-{{index .path.segments 3}}.yaml'
          - '$values/helm/{{index .path.segments 1}}/clusters/values-{{.name}}.yaml'  # TBD
          ignoreMissingValueFiles: true


      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{if eq (index .path.segments 1) "cilium" "sealed-secrets"}}kube-system{{else}}{{index .path.segments 3}}-{{index .path.segments 1}}{{end}}'
        namespace: '{{index .path.segments 3}}-{{index .path.segments 1}}'

      # Sync policy
      syncPolicy:
        # managedNamespaceMetadata:
        #   labels:
        #     pod-security.kubernetes.io/enforce: privileged
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      
